bairros = [

"Aclimação",
"Alto Umuarama",
"Alvorada",
"Carajás",
"Chácaras Panorama",
"Chácaras Tubalina",
"Cidade Jardim",
"Custódio Pereira",
"Distrito Industrial",
"Dona Zulmira",
"Gávea",
"Granada",
"Grand Ville",
"Granja Marileusa",
"Guarani",
"Jaraguá",
"Jardim Brasília",
"Jardim Canaã",
"Jardim das Palmeiras",
"Jardim Europa",
"Jardim Holanda",
"Jardim Inconfidência",
"Jardim Ipanema",
"Jardim Karaíba",
"Jardim Patrícia",
"Jardim Sul",
"Lagoinha",
"Laranjeiras",
"Luizote de Freitas",
"Mansões Aeroporto",
"Mansour",
"Maravilha",
"Marta Helena",
"Minas Gerais",
"Monte Hebron",
"Morada da Colina",
"Morada do Sol",
"Morada dos Pássaros",
"Morada Nova",
"Morumbi",
"Nossa Senhora das Graças",
"Nova Uberlândia",
"Novo Mundo",
"Pacaembu",
"Pampulha",
"Patrimônio",
"Planalto",
"Portal do Vale",
"Presidente Roosevelt",
"Residencial Gramado",
"Residencial Integração[3]",
"Residencial Pequis",
"Santa Luzia",
"Santa Mônica",
"Santa Rosa",
"São Jorge",
"São José",
"Saraiva",
"Segismundo Pereira",
"Shopping Park",
"Taiaman",
"Tibery",
"Tocantins [2]",
"Tubalina",
"Umuarama",
"Vigilato Pereira",

]

regioes = [

"Centro",
"Norte",
"Sul",
"Leste",
"Oeste"

]